# -*- coding: utf-8 -*-
"""trabajo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18L-jdkGU6uGHQsoK4cEvds1Owe5Z48rt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pylab import subplots
import seaborn as sns

archivo = "/content/drive/MyDrive/trabajo/notas.xlsx"
df = pd.read_excel(archivo)



print("Presione A, si desea ingresar datos(nueva fila)")
print("Presione B, si desea filtrar por medio de caracteristicas")
print("Presione C, si desea solicitar graficos")
print("Presione D, si desea datos estadisticos")
print("Presione E, si desea agregar una nueva columna")
print("Presione otro comando, si desea cerrar el programa")

def usuario_decision():
  decision = input("Que opcion elige:")
  if decision == "A":
    estado = 1
  elif decision == "B":
    estado = 2
  elif decision == "C":
    estado = 3
  elif decision == "D":
    estado = 4
  elif decision == "E":
    estado = 5
  else:
    estado =6
  return estado


def Columns(df):                    #me retorna la en columna en lista
  columnas = df.columns
  list_columnas = list(columnas)
  return list_columnas

def Anadir_Filas():
  global df
  dicc_fila = {}
  columnas_df = Columns(df)  
  for columna in columnas_df:
    dicc_fila[columna] = input("Ingrese el valor de la columna {} ".format(columna))
  df= df.append(dicc_fila,ignore_index = True)
  display(df)

def Filtro_Filas():
  global df
  print("Desde que fila: ")
  inf = int(input("Escriba limite inferior: "))
  print("Hasta que fila: ")
  sup = int(input("Escriba limite superior de busquedad: "))
  filas_n = df.iloc[inf:sup+1]
  print(filas_n)

def Filtro_Colum():
  global df
  colu = input("Nombre de la columna que desea mostrar: ")
  col_n = df[colu]
  print(col_n)


def Filtro():
  global df
  print("Presione 'A' si desea mostrar toda una columna")
  print("Presione 'B' si desea mostrar toda una fila")
  print("Presione 'C' si desea buscar especificamente en alguna columna")
  opcion1 = input("Que opcion escoge: ")
  while opcion1 !="A" and opcion1!="B" and opcion1 !="C":
    print("Error... debe presionar el comando que le corresponde a su opcion : ")
    opcion1 = input("Que opcion escoge: ")
  if opcion1 == "A":
    Filtro_Colum()
  elif opcion1 == "B":
    Filtro_Filas()
  elif opcion1 == "C":
    name_columna = input("Escriba el nombre de la columna: ")
    condicion = input("Escriba que dato busca en la columna {} ".format(name_columna))
    filtro = df.loc[df[name_columna]==condicion]
    print(filtro)

def Agregar_Columna():
  global df
  valo_lista =[]
  nombre = input("Nombre de la columna nueva: ")
  cant = df["DNI"].count()
  for i in range(cant):
    valores = int(input("Ingrese valo: "))
    valo_lista.append(valores)
  df[nombre]=valo_lista
  return df

def Datos_Estadisticos():
  global df
  print("Presione A si desea los datos de toda la tabla")
  print("Presione B si desea datos especificos")
  opcion = input("Que opcion elige:")
  while opcion!="A" and opcion!="B":
    print("Error... Debe presionar el comando referente a la opcion")
    opcion = input("Que opcion elige:")
  if opcion == "A":
    des = df.describe()
    display(des)
  elif opcion == "B":
    print("Presione 'C' si solo desea de una columna")
    print("Presione 'D' si desea la columna diferenciada por sexo")
    print("Presione 'E' si desea la columna diferenciada por PA")
    opcion1 =input("Que opcion elige:")
    while opcion1 !="C" and opcion1 != "D" and opcion1 != "E":
      print("Error... Debe presionar el comando referente a la opcion")
      opcion1 = input("Que opcion elige:")      
    col_df = input("Escriba la columna: ")
    if opcion1 =="C":
      des = df[col_df].describe()
      display(des)
    elif opcion1 =="D":
      print("HOMBRES")
      des = df.query("Sexo==1")[col_df].describe() 
      display(des)
      print("MUJERES")
      des = df.query("Sexo==0")[col_df].describe() 
      display(des)
    elif opcion1 == "E":
      print("ING.INDUSTRIAL Y DE SISTEMAS")
      des = df.query("PA_number == 1")[col_df].describe()
      display(des)
      print("ING.CIVIL")
      des = df.query("PA_number == 2")[col_df].describe()
      display(des)
      print("ING.MECANICA ELECTRICA")
      des = df.query("PA_number == 3")[col_df].describe()
      display(des)
     

def Histograma():
  plt.style.use('seaborn-white')  
  Valor1 = input("Ingrese la columna: ")
  cant_bins = int(input("Cantidad de intervalos que desea: "))
  valor2 = list(df[Valor1])
  valor_arr = np.array(valor2)
  plt.hist(valor_arr, bins= cant_bins,alpha=0.6,histtype="bar",color="steelblue",edgecolor="black")
  plt.show()

def Diferenciacion():
  print("Desea diferenciar un curso entre sexo, presione 'S'")
  print("Desea diferencia un curso entre PA, presione 'P'")
  opcion3 = input("Que opcion elige")
  while opcion3 != "S" and opcion3 != "P":
    print("Debe elegir una opcion")
    opcion3 = input("Que opcion elige")
  curso = input("Que curso escoge: ")
  if opcion3 == "S":
    sns.displot(df,x=curso,hue="Sexo")
    plt.show()
  if opcion3 =="P":
    sns.displot(df,x=curso,hue="PA")
    plt.show()


def Soli_Graficos():
  print("Presione 'H' si desea graficar un histograma de una columna")
  print("Presione 'HC' si desea graficar un histograma por separacion de grupos")
  grafico = input("Que ocion desea hacer: ")
  while grafico!="H" and grafico!="HC":
    print("Entrada erronea")
    grafico = input("Que ocion desea hacer: ")
  if grafico == "H":
    Histograma()
  elif grafico == "HC":
    Diferenciacion()

while True:
  estado = usuario_decision ()
  if estado == 1:
    Anadir_Filas()
  elif estado == 2:
    Filtro()
  elif estado == 3:
    Soli_Graficos()
  elif estado == 4:
    Datos_Estadisticos()
  elif estado == 5:
    Agregar_Columna()
  elif estado == 6:
    print("Cerrar Programa")
    break